### ISSUE TITLE
Button text overlapping

### ISSUE THREAD

**Issue by MrMemeikyu** [MrMemeikyu/Heist-Earpiece#2]
Difficult to see, but majority of buttons have a layer of text appearing to be below the initial layer of text
<img width="130" alt="Screenshot 2024-11-11 at 12 47 53 PM" src="https://github.com/user-attachments/assets/34983166-0b58-47e7-b102-a2c0a7b6919e">

Unsure where or why it is happening, or if it even is a problem, but buttons are assigned text once and only one set of 16 buttons are created

**Comment by MrMemeikyu** [comment]
Turns out there are multiple buttons because _ready() is being run twice (for god knows why)

**Comment by paralinguist** [comment]
Ready was being run twice because somewhere in the project, the code file had been set as an "autoload" thing?

EIther way, I ended up remaking the entire scene and moving code across. Seems much happier.

**Comment by MrMemeikyu** [comment]
I probably should've updated this or left a comment sooner but I did end up resolving the issue, I set the script as global earlier when messing with buttons which apparently caused a bunch of other issues including this
